### ISSUE TITLE
An error about cuDNN:CUDNN_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by Udonnoodle** [jzbontar/mc-cnn#11]
hi,Jure. I am a newer in cnn and stereo vision. and I have read your paper about mc-cnn.However, when I run your code on my computer. An error occurs. As show in fig
![screenshot from 2016-11-08 17-55-09](https://cloud.githubusercontent.com/assets/13975110/20098799/810994da-a5f0-11e6-8a6f-4cb031426af1.png)
My computer's GPU is NVIDIA GTX650 with 1g memory. if I can run your code ,I will buy a better GPU to learning cnn.
I have search this error in Google,they say the GPU memory is too small to run code.How can I change your code to decrease the GPU  memory.or some solution else?

**Comment by Udonnoodle** [comment]
I have slove this problem ,and anthor problem about cuda complie setting.It run on my  computer now. Thank you for sharing code!

**Comment by shuluoshu** [comment]
@Udonnoodle , Hi, I met a similar problem after I update the torch version to the newest one, the error is as follows: could you help me out?
![error](https://cloud.githubusercontent.com/assets/17999845/23250677/213fc7a6-f9e5-11e6-93cc-6a6b9212ffc7.png)
My cuda is v7.5 and I use cudnnV7.0
Thanks a lot !

**Comment by shuluoshu** [comment]
I solved the problem by comment 'cunn.benchmark=True', but I don't know why.

**Comment by shuluoshu** [comment]
I solved the problem by comment 'cudnn.benchmark=True', but I don't know why.

**Comment by laoreja** [comment]
cudnn.benchmark=True
on the doc, it says:
uses the inbuilt cudnn auto-tuner to find the fastest convolution algorithms.
If this is set to false, uses some in-built heuristics that might not always be fastest.

by default cudnn.benchmark is set to false. Setting to true will improve performance, at the expense of using more memory. The input shape should be the same for each batch, otherwise autotune will re-run for each batch, causing a huge slow-down.
